# Generated by Django 3.1.4 on 2020-12-13 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=255)),
                ('cuisine', models.CharField(choices=[('European', 'European'), ('American', 'American'), ('Asian', 'Asian'), ('Bakery & Cakes', 'Bakery And Cakes'), ('Beverages', 'Beverages'), ('Chinese', 'Chinese'), ('Desserts', 'Desserts'), ('Fast Food', 'Fast Food'), ('Fusion', 'Fusion'), ('Indian', 'Indian'), ('Indonesian', 'Indonesian'), ('International', 'International'), ('Italian', 'Italian'), ('Japanese', 'Japanese'), ('Korean', 'Korean'), ('Malay', 'Malay'), ('Mediterranean', 'Mediterranean'), ('Peranakan', 'Peranakan'), ('Pizza', 'Pizza'), ('Seafood', 'Seafood'), ('Thai', 'Thai'), ('Western', 'Western')], default='Malay', max_length=50)),
                ('picture', models.CharField(max_length=255)),
                ('average_rating', models.FloatField(default=0, null=True)),
                ('is_registered', models.BooleanField(default=False, null=True)),
                ('max_pax_reservations', models.IntegerField(default=5, null=True)),
                ('capacity', models.IntegerField(default=50, null=True)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
            ],
        ),
    ]
