# Generated by Django 3.1.4 on 2020-12-16 05:00

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_restaurant_restaurant_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='picture',
            field=cloudinary.models.CloudinaryField(default='https://s3.amazonaws.com/vulture-food-photos/defaultvulture.png', max_length=255, verbose_name='image'),
        ),
    ]
