# Generated by Django 3.1.4 on 2020-12-17 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_auto_20201216_0500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='cuisine',
            field=models.CharField(choices=[('European', 'European'), ('American', 'American'), ('Asian', 'Asian'), ('Bakery & Cakes', 'Bakery And Cakes'), ('Beverages', 'Beverages'), ('Chinese', 'Chinese'), ('Desserts', 'Desserts'), ('Fast Food', 'Fast Food'), ('Fusion', 'Fusion'), ('Indian', 'Indian'), ('Indonesian', 'Indonesian'), ('International', 'International'), ('Italian', 'Italian'), ('Japanese', 'Japanese'), ('Korean', 'Korean'), ('Malay', 'Malay'), ('Mediterranean', 'Mediterranean'), ('Peranakan', 'Peranakan'), ('Pizza', 'Pizza'), ('Seafood', 'Seafood'), ('Thai', 'Thai'), ('Western', 'Western')], default='None', max_length=50),
        ),
    ]
