# Generated by Django 3.1.4 on 2020-12-17 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_auto_20201217_0454'),
        ('restaurants', '0004_auto_20201217_0751'),
    ]

    operations = [
    ]
