# Generated by Django 3.1.4 on 2020-12-16 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_restaurant_restaurant_id'),
        ('accounts', '0002_userprofile_favourites'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='restaurant_owned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='restaurants.restaurant'),
        ),
    ]
