# Generated by Django 3.1.4 on 2020-12-16 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_restaurant_restaurant_id'),
        ('accounts', '0003_userprofile_restaurant_owned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='restaurant_owned',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='restaurant_owned',
            field=models.ManyToManyField(blank=True, related_name='owners', to='restaurants.Restaurant'),
        ),
    ]
