# Generated by Django 3.1.4 on 2020-12-15 05:43

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0002_restaurant_restaurant_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', cloudinary.models.CloudinaryField(default='https://s3.amazonaws.com/vulture-food-photos/defaultvulture.png', max_length=255, verbose_name='review_image')),
                ('review_title', models.CharField(max_length=50, null=True)),
                ('review_body', models.TextField()),
                ('taste_rating', models.IntegerField(default=1)),
                ('service_rating', models.IntegerField(default=1)),
                ('cleanliness_rating', models.IntegerField(default=1)),
                ('average_rating', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='restaurants.restaurant')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
